### ISSUE TITLE
Error: Could not find or load main class uk.ac.ebi.ena.ftp.gui.Main

### ISSUE THREAD

**Issue by tseemann** [enasequence/ena-ftp-downloader#2]
I keep getting this error when I try to run the JAR.

I suspect I am doing somethign wrong, but I followed the instructions.

```
% java -showversion
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-b12)
OpenJDK 64-Bit Server VM (build 25.131-b12, mixed mode)

% java -jar ena-ftp-downloader-v1.0.jar
Error: Could not find or load main class uk.ac.ebi.ena.ftp.gui.Main

% java -jar $PWD/ena-ftp-downloader-v1.0.jar
Error: Could not find or load main class uk.ac.ebi.ena.ftp.gui.Main
```

**Comment by suranjayathilaka** [comment]
Thanks for reporting this. I'm looking into it.

**Comment by suranjayathilaka** [comment]
This application is written using JavaFX, and it seems that unfortunately OpenJDK does not include JavaFX by default. 

Your best option would to install Oracle Java 8 (JRE or JDK) and use that to execute the jar file. 
Or you could try to install JavaFX for OpenJDK using
```
sudo apt-get install openjfx 
```
(or the equivalent for your OS)

My apologies for not specifying this requirement in the documentation.

**Comment by tseemann** [comment]
I do not use a Debian based system, I can not use the `apt-get` route.

I have never encountered a JavaFX app, but I see it is a 'successor' to Swing and the long gone AWT.

I  would normally expect EBI/ENA to use a more open alternative.

**Comment by minisciencegirl** [comment]
I am having the same issue. 

I have java-8-oracle installed and also did `sudo apt-get install openjfx`, but am receiving the same error.
