### ISSUE TITLE
Which JAR file?

### ISSUE THREAD

**Issue by ag1805x** [enasequence/ena-ftp-downloader#4]
> Download the latest release (.zip file) from the Releases section of the GitHub project and extract it to a location of your choice. The archive contains an executable jar which contains all dependencies

I downloaded the zip file but couldn't locate any jar file in it?

**Comment by suranjayathilaka** [comment]
Did you download the source zip file perhaps? The executable file is below:
[Release](https://github.com/enasequence/ena-ftp-downloader/files/1527471/ena-file-downloader-v1.2.1.zip)
