### ISSUE TITLE
ena-ftp-downloader is very very slow

### ISSUE THREAD

**Issue by minisciencegirl** [enasequence/ena-ftp-downloader#6]
Hi, I am using ena-ftp-downloader to download what I think is a small to medium dataset (~135G). However, it has taken me over 3 days and the download is still not complete! I've downloaded the equivalent dataset from NCBI using command-line sratools in less than 3 hours, with minimum hands-on interaction time. I know it is not an issue with my internet upload or download speed. Any suggestions on improving this?

**Comment by suranjayathilaka** [comment]
Hi!
Sorry about the very late response. Are you still facing these speed issues? I could make a couple of suggestions.
1. Use Aspera for downloads
2. Try the python based scripts for bulk download https://github.com/enasequence/enaBrowserTools/   (also can use Aspera)

best regards,
Suran
