### ISSUE TITLE
Downloading stopped due to an error and error in md5 column 

### ISSUE THREAD

**Issue by Deepakshyl** [enasequence/ena-ftp-downloader#7]
"Downloading stopped due to an error" and  there is a red "X" mark in the column  of md5. And the downloading stops 
![capture](https://user-images.githubusercontent.com/45304046/48964651-63b86680-efd2-11e8-8f23-040333aecb57.JPG)

**Comment by soleilll** [comment]
hi,I have the same problem. Do you have a solution?

**Comment by Deepakshyl** [comment]
> hi,I have the same problem. Do you have a solution?

s i did solved it. add aspera connect to connection settings.
